{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "8fbd9697-5f5f-4351-bbe4-98a465dcc384",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Image 0 downloaded successfully\n",
      "Image 1 downloaded successfully\n",
      "Image 2 downloaded successfully\n",
      "Image 3 downloaded successfully\n",
      "Image 4 downloaded successfully\n",
      "Image 5 downloaded successfully\n",
      "Image 6 downloaded successfully\n",
      "Image 7 downloaded successfully\n",
      "Image 8 downloaded successfully\n",
      "Image 9 downloaded successfully\n",
      "Image 10 downloaded successfully\n",
      "Image 11 downloaded successfully\n",
      "Image 12 downloaded successfully\n",
      "Image 13 downloaded successfully\n",
      "Image 14 downloaded successfully\n",
      "Image 15 downloaded successfully\n",
      "Image 16 downloaded successfully\n",
      "Image 17 downloaded successfully\n",
      "Image 18 downloaded successfully\n",
      "Image 19 downloaded successfully\n",
      "Image 20 downloaded successfully\n",
      "Image 21 downloaded successfully\n",
      "Image 22 downloaded successfully\n",
      "Image 23 downloaded successfully\n",
      "Image 24 downloaded successfully\n",
      "Image 25 downloaded successfully\n",
      "Image 26 downloaded successfully\n",
      "Image 27 downloaded successfully\n",
      "Image 28 downloaded successfully\n",
      "Image 29 downloaded successfully\n",
      "Image 30 downloaded successfully\n",
      "Image 31 downloaded successfully\n",
      "Image 32 downloaded successfully\n",
      "Image 33 downloaded successfully\n",
      "Image 34 downloaded successfully\n",
      "Image 35 downloaded successfully\n",
      "Image 36 downloaded successfully\n",
      "Image 37 downloaded successfully\n",
      "Image 38 downloaded successfully\n",
      "Image 39 downloaded successfully\n",
      "Image 40 downloaded successfully\n",
      "Image 41 downloaded successfully\n",
      "Image 42 downloaded successfully\n",
      "Image 43 downloaded successfully\n",
      "Image 44 downloaded successfully\n",
      "Image 45 downloaded successfully\n",
      "Image 46 downloaded successfully\n",
      "Image 47 downloaded successfully\n",
      "Image 48 downloaded successfully\n",
      "Image 49 downloaded successfully\n",
      "Image 50 downloaded successfully\n",
      "Image 51 downloaded successfully\n",
      "Image 52 downloaded successfully\n",
      "Image 53 downloaded successfully\n",
      "Image 54 downloaded successfully\n",
      "Image 55 downloaded successfully\n",
      "Image 56 downloaded successfully\n",
      "Image 57 downloaded successfully\n",
      "Image 58 downloaded successfully\n",
      "Image 59 downloaded successfully\n",
      "Image 60 downloaded successfully\n",
      "Image 61 downloaded successfully\n",
      "Image 62 downloaded successfully\n",
      "Image 63 downloaded successfully\n",
      "Image 64 downloaded successfully\n",
      "Image 65 downloaded successfully\n",
      "Image 66 downloaded successfully\n",
      "Image 67 downloaded successfully\n",
      "Image 68 downloaded successfully\n",
      "Image 69 downloaded successfully\n",
      "Image 70 downloaded successfully\n",
      "Image 71 downloaded successfully\n",
      "Image 72 downloaded successfully\n",
      "Image 73 downloaded successfully\n",
      "Image 74 downloaded successfully\n",
      "Image 75 downloaded successfully\n",
      "Image 76 downloaded successfully\n",
      "Image 77 downloaded successfully\n",
      "Image 78 downloaded successfully\n",
      "Image 79 downloaded successfully\n",
      "Image 80 downloaded successfully\n",
      "Image 81 downloaded successfully\n",
      "Image 82 downloaded successfully\n",
      "Image 83 downloaded successfully\n",
      "Image 84 downloaded successfully\n",
      "Image 85 downloaded successfully\n",
      "Image 86 downloaded successfully\n",
      "Image 87 downloaded successfully\n",
      "Image 88 downloaded successfully\n",
      "Image 89 downloaded successfully\n",
      "Image 90 downloaded successfully\n",
      "Image 91 downloaded successfully\n",
      "Image 92 downloaded successfully\n",
      "Image 93 downloaded successfully\n",
      "Image 94 downloaded successfully\n",
      "Image 95 downloaded successfully\n",
      "Image 96 downloaded successfully\n",
      "Image 97 downloaded successfully\n",
      "Image 98 downloaded successfully\n",
      "Image 99 downloaded successfully\n",
      "Image 100 downloaded successfully\n",
      "Image 101 downloaded successfully\n",
      "Image 102 downloaded successfully\n",
      "Image 103 downloaded successfully\n",
      "Image 104 downloaded successfully\n",
      "Image 105 downloaded successfully\n",
      "Image 106 downloaded successfully\n",
      "Image 107 downloaded successfully\n",
      "Image 108 downloaded successfully\n",
      "Image 109 downloaded successfully\n",
      "Image 110 downloaded successfully\n",
      "Image 111 downloaded successfully\n",
      "Image 112 downloaded successfully\n",
      "Image 113 downloaded successfully\n",
      "Image 114 downloaded successfully\n",
      "Image 115 downloaded successfully\n",
      "Image 116 downloaded successfully\n",
      "Image 117 downloaded successfully\n",
      "Image 118 downloaded successfully\n",
      "Image 119 downloaded successfully\n",
      "Image 120 downloaded successfully\n",
      "Image 121 downloaded successfully\n",
      "Image 122 downloaded successfully\n",
      "Image 123 downloaded successfully\n",
      "Image 124 downloaded successfully\n",
      "Image 125 downloaded successfully\n",
      "Image 126 downloaded successfully\n",
      "Image 127 downloaded successfully\n",
      "Image 128 downloaded successfully\n",
      "Image 129 downloaded successfully\n",
      "Image 130 downloaded successfully\n",
      "Image 131 downloaded successfully\n",
      "Image 132 downloaded successfully\n",
      "Image 133 downloaded successfully\n",
      "Image 134 downloaded successfully\n",
      "Image 135 downloaded successfully\n",
      "Image 136 downloaded successfully\n",
      "Image 137 downloaded successfully\n",
      "Image 138 downloaded successfully\n",
      "Image 139 downloaded successfully\n",
      "Image 140 downloaded successfully\n",
      "Image 141 downloaded successfully\n",
      "Image 142 downloaded successfully\n",
      "Image 143 downloaded successfully\n",
      "Image 144 downloaded successfully\n",
      "Image 145 downloaded successfully\n",
      "Image 146 downloaded successfully\n",
      "Image 147 downloaded successfully\n",
      "Image 148 downloaded successfully\n",
      "Image 149 downloaded successfully\n",
      "Image 150 downloaded successfully\n",
      "Image 151 downloaded successfully\n",
      "Image 152 downloaded successfully\n",
      "Image 153 downloaded successfully\n",
      "Image 154 downloaded successfully\n",
      "Image 155 downloaded successfully\n",
      "Image 156 downloaded successfully\n",
      "Image 157 downloaded successfully\n",
      "Image 158 downloaded successfully\n",
      "Image 159 downloaded successfully\n",
      "Image 160 downloaded successfully\n",
      "Image 161 downloaded successfully\n",
      "Image 162 downloaded successfully\n",
      "Image 163 downloaded successfully\n",
      "Image 164 downloaded successfully\n",
      "Image 165 downloaded successfully\n",
      "Image 166 downloaded successfully\n",
      "Image 167 downloaded successfully\n",
      "Image 168 downloaded successfully\n",
      "Image 169 downloaded successfully\n",
      "Image 170 downloaded successfully\n",
      "Image 171 downloaded successfully\n",
      "Image 172 downloaded successfully\n",
      "Image 173 downloaded successfully\n",
      "Image 174 downloaded successfully\n",
      "Image 175 downloaded successfully\n",
      "Image 176 downloaded successfully\n",
      "Image 177 downloaded successfully\n",
      "Image 178 downloaded successfully\n",
      "Image 179 downloaded successfully\n",
      "Image 180 downloaded successfully\n",
      "Image 181 downloaded successfully\n",
      "Image 182 downloaded successfully\n",
      "Image 183 downloaded successfully\n",
      "Image 184 downloaded successfully\n",
      "Image 185 downloaded successfully\n",
      "Image 186 downloaded successfully\n",
      "Image 187 downloaded successfully\n",
      "Image 188 downloaded successfully\n",
      "Image 189 downloaded successfully\n",
      "Image 190 downloaded successfully\n",
      "Image 191 downloaded successfully\n",
      "Image 192 downloaded successfully\n",
      "Image 193 downloaded successfully\n",
      "Image 194 downloaded successfully\n",
      "Image 195 downloaded successfully\n",
      "Image 196 downloaded successfully\n",
      "Image 197 downloaded successfully\n",
      "Image 198 downloaded successfully\n",
      "Image 199 downloaded successfully\n",
      "Image 200 downloaded successfully\n",
      "Image 201 downloaded successfully\n",
      "Image 202 downloaded successfully\n",
      "Image 203 downloaded successfully\n",
      "Image 204 downloaded successfully\n",
      "Image 205 downloaded successfully\n",
      "Image 206 downloaded successfully\n",
      "Image 207 downloaded successfully\n",
      "Image 208 downloaded successfully\n",
      "Image 209 downloaded successfully\n",
      "Image 210 downloaded successfully\n",
      "Image 211 downloaded successfully\n",
      "Image 212 downloaded successfully\n",
      "Image 213 downloaded successfully\n",
      "Image 214 downloaded successfully\n",
      "Image 215 downloaded successfully\n",
      "Image 216 downloaded successfully\n",
      "Image 217 downloaded successfully\n",
      "Image 218 downloaded successfully\n",
      "Image 219 downloaded successfully\n",
      "Image 220 downloaded successfully\n",
      "Image 221 downloaded successfully\n",
      "Image 222 downloaded successfully\n",
      "Image 223 downloaded successfully\n",
      "Image 224 downloaded successfully\n",
      "Image 225 downloaded successfully\n",
      "Image 226 downloaded successfully\n",
      "Image 227 downloaded successfully\n",
      "Image 228 downloaded successfully\n",
      "Image 229 downloaded successfully\n",
      "Image 230 downloaded successfully\n",
      "Image 231 downloaded successfully\n",
      "Image 232 downloaded successfully\n",
      "Image 233 downloaded successfully\n",
      "Image 234 downloaded successfully\n",
      "Image 235 downloaded successfully\n",
      "Image 236 downloaded successfully\n",
      "Image 237 downloaded successfully\n",
      "Image 238 downloaded successfully\n",
      "Image 239 downloaded successfully\n",
      "Image 240 downloaded successfully\n",
      "Image 241 downloaded successfully\n",
      "Image 242 downloaded successfully\n",
      "Image 243 downloaded successfully\n",
      "Image 244 downloaded successfully\n",
      "Image 245 downloaded successfully\n",
      "Image 246 downloaded successfully\n",
      "Image 247 downloaded successfully\n",
      "Image 248 downloaded successfully\n",
      "Image 249 downloaded successfully\n",
      "Image 250 downloaded successfully\n",
      "Image 251 downloaded successfully\n",
      "Image 252 downloaded successfully\n",
      "Image 253 downloaded successfully\n",
      "Image 254 downloaded successfully\n",
      "Image 255 downloaded successfully\n",
      "Image 256 downloaded successfully\n",
      "Image 257 downloaded successfully\n",
      "Image 258 downloaded successfully\n",
      "Image 259 downloaded successfully\n",
      "Image 260 downloaded successfully\n",
      "Image 261 downloaded successfully\n",
      "Image 262 downloaded successfully\n",
      "Image 263 downloaded successfully\n",
      "Image 264 downloaded successfully\n",
      "Image 265 downloaded successfully\n",
      "Image 266 downloaded successfully\n",
      "Image 267 downloaded successfully\n",
      "Image 268 downloaded successfully\n",
      "Image 269 downloaded successfully\n",
      "Image 270 downloaded successfully\n",
      "Image 271 downloaded successfully\n",
      "Image 272 downloaded successfully\n",
      "Image 273 downloaded successfully\n",
      "Image 274 downloaded successfully\n",
      "Image 275 downloaded successfully\n",
      "Image 276 downloaded successfully\n",
      "Image 277 downloaded successfully\n",
      "Image 278 downloaded successfully\n",
      "Image 279 downloaded successfully\n",
      "Image 280 downloaded successfully\n",
      "Image 281 downloaded successfully\n",
      "Image 282 downloaded successfully\n",
      "Image 283 downloaded successfully\n",
      "Image 284 downloaded successfully\n",
      "Image 285 downloaded successfully\n",
      "Image 286 downloaded successfully\n",
      "Image 287 downloaded successfully\n",
      "Image 288 downloaded successfully\n",
      "Image 289 downloaded successfully\n",
      "Image 290 downloaded successfully\n",
      "Image 291 downloaded successfully\n",
      "Image 292 downloaded successfully\n",
      "Image 293 downloaded successfully\n",
      "Image 294 downloaded successfully\n",
      "Image 295 downloaded successfully\n",
      "Image 296 downloaded successfully\n",
      "Image 297 downloaded successfully\n",
      "Image 298 downloaded successfully\n",
      "Image 299 downloaded successfully\n",
      "Image 300 downloaded successfully\n",
      "Image 301 downloaded successfully\n",
      "Image 302 downloaded successfully\n",
      "Image 303 downloaded successfully\n",
      "Image 304 downloaded successfully\n",
      "Image 305 downloaded successfully\n",
      "Image 306 downloaded successfully\n",
      "Image 307 downloaded successfully\n",
      "Image 308 downloaded successfully\n",
      "Image 309 downloaded successfully\n",
      "Image 310 downloaded successfully\n",
      "Image 311 downloaded successfully\n",
      "Image 312 downloaded successfully\n",
      "Image 313 downloaded successfully\n",
      "Image 314 downloaded successfully\n",
      "Image 315 downloaded successfully\n",
      "Image 316 downloaded successfully\n",
      "Image 317 downloaded successfully\n",
      "Image 318 downloaded successfully\n",
      "Image 319 downloaded successfully\n",
      "Image 320 downloaded successfully\n",
      "Image 321 downloaded successfully\n",
      "Image 322 downloaded successfully\n",
      "Image 323 downloaded successfully\n",
      "Image 324 downloaded successfully\n",
      "Image 325 downloaded successfully\n",
      "Image 326 downloaded successfully\n",
      "Image 327 downloaded successfully\n",
      "Image 328 downloaded successfully\n",
      "Image 329 downloaded successfully\n",
      "Image 330 downloaded successfully\n",
      "Image 331 downloaded successfully\n",
      "Image 332 downloaded successfully\n",
      "Image 333 downloaded successfully\n",
      "Image 334 downloaded successfully\n",
      "Image 335 downloaded successfully\n",
      "Image 336 downloaded successfully\n",
      "Image 337 downloaded successfully\n",
      "Image 338 downloaded successfully\n",
      "Image 339 downloaded successfully\n",
      "Image 340 downloaded successfully\n",
      "Image 341 downloaded successfully\n",
      "Image 342 downloaded successfully\n",
      "Image 343 downloaded successfully\n",
      "Image 344 downloaded successfully\n",
      "Image 345 downloaded successfully\n",
      "Image 346 downloaded successfully\n",
      "Image 347 downloaded successfully\n",
      "Image 348 downloaded successfully\n",
      "Image 349 downloaded successfully\n",
      "Image 350 downloaded successfully\n",
      "Image 351 downloaded successfully\n",
      "Image 352 downloaded successfully\n",
      "Image 353 downloaded successfully\n",
      "Image 354 downloaded successfully\n",
      "Image 355 downloaded successfully\n",
      "Image 356 downloaded successfully\n",
      "Image 357 downloaded successfully\n",
      "Image 358 downloaded successfully\n",
      "Image 359 downloaded successfully\n",
      "Image 360 downloaded successfully\n",
      "Image 361 downloaded successfully\n",
      "Image 362 downloaded successfully\n",
      "Image 363 downloaded successfully\n",
      "Image 364 downloaded successfully\n",
      "Image 365 downloaded successfully\n",
      "Image 366 downloaded successfully\n",
      "Image 367 downloaded successfully\n",
      "Image 368 downloaded successfully\n",
      "Image 369 downloaded successfully\n",
      "Image 370 downloaded successfully\n",
      "Image 371 downloaded successfully\n",
      "Image 372 downloaded successfully\n",
      "Image 373 downloaded successfully\n",
      "Image 374 downloaded successfully\n",
      "Image 375 downloaded successfully\n",
      "Image 376 downloaded successfully\n",
      "Image 377 downloaded successfully\n",
      "Image 378 downloaded successfully\n",
      "Image 379 downloaded successfully\n",
      "Image 380 downloaded successfully\n",
      "Image 381 downloaded successfully\n",
      "Image 382 downloaded successfully\n",
      "Image 383 downloaded successfully\n",
      "Image 384 downloaded successfully\n",
      "Image 385 downloaded successfully\n",
      "Image 386 downloaded successfully\n",
      "Image 387 downloaded successfully\n",
      "Image 388 downloaded successfully\n",
      "Image 389 downloaded successfully\n",
      "Image 390 downloaded successfully\n",
      "Image 391 downloaded successfully\n",
      "Image 392 downloaded successfully\n",
      "Image 393 downloaded successfully\n",
      "Image 394 downloaded successfully\n",
      "Image 395 downloaded successfully\n",
      "Image 396 downloaded successfully\n",
      "Image 397 downloaded successfully\n",
      "Image 398 downloaded successfully\n",
      "Image 399 downloaded successfully\n",
      "Image 400 downloaded successfully\n",
      "Image 401 downloaded successfully\n",
      "Image 402 downloaded successfully\n",
      "Image 403 downloaded successfully\n",
      "Image 404 downloaded successfully\n",
      "Image 405 downloaded successfully\n",
      "Image 406 downloaded successfully\n",
      "Image 407 downloaded successfully\n",
      "Image 408 downloaded successfully\n",
      "Image 409 downloaded successfully\n",
      "Image 410 downloaded successfully\n",
      "Image 411 downloaded successfully\n",
      "Image 412 downloaded successfully\n",
      "Image 413 downloaded successfully\n",
      "Image 414 downloaded successfully\n",
      "Image 415 downloaded successfully\n",
      "Image 416 downloaded successfully\n",
      "Image 417 downloaded successfully\n",
      "Image 418 downloaded successfully\n",
      "Image 419 downloaded successfully\n",
      "Image 420 downloaded successfully\n",
      "Image 421 downloaded successfully\n",
      "Image 422 downloaded successfully\n",
      "Image 423 downloaded successfully\n",
      "Image 424 downloaded successfully\n",
      "Image 425 downloaded successfully\n",
      "Image 426 downloaded successfully\n",
      "Image 427 downloaded successfully\n",
      "Image 428 downloaded successfully\n",
      "Image 429 downloaded successfully\n",
      "Image 430 downloaded successfully\n",
      "Image 431 downloaded successfully\n",
      "Image 432 downloaded successfully\n",
      "Image 433 downloaded successfully\n",
      "Image 434 downloaded successfully\n",
      "Image 435 downloaded successfully\n",
      "Image 436 downloaded successfully\n",
      "Image 437 downloaded successfully\n",
      "Image 438 downloaded successfully\n",
      "Image 439 downloaded successfully\n",
      "Image 440 downloaded successfully\n",
      "Image 441 downloaded successfully\n",
      "Image 442 downloaded successfully\n",
      "Image 443 downloaded successfully\n",
      "Image 444 downloaded successfully\n",
      "Image 445 downloaded successfully\n",
      "Image 446 downloaded successfully\n"
     ]
    }
   ],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "import time\n",
    "import os\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "# Initialize the browser\n",
    "driver = webdriver.Chrome() # Asegúrate de tener el driver de Chrome instalado\n",
    "\n",
    "# We maximize the browser\n",
    "driver.maximize_window()\n",
    "\n",
    "# Keyword to search images on Google\n",
    "keyword = \"gatos\"\n",
    "\n",
    "# Navigating to the Google image search page\n",
    "url = \"https://www.google.com/search?tbm=isch&q=\"\n",
    "driver.get(url + keyword)\n",
    "\n",
    "# Wait a moment for the page to load\n",
    "time.sleep(2)\n",
    "\n",
    "# Scrolling to load more images\n",
    "for _ in range(5):\n",
    "    driver.execute_script(\"window.scrollTo(0, document.body.scrollHeight);\")\n",
    "    time.sleep(2)\n",
    "\n",
    "# Obtain links to images\n",
    "soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "image_links = []\n",
    "for img in soup.find_all('img'):\n",
    "    if img.get('data-src'):\n",
    "        image_links.append(img.get('data-src'))\n",
    "\n",
    "# Create a directory to store downloaded images\n",
    "if not os.path.exists(keyword):\n",
    "    os.makedirs(keyword)\n",
    "\n",
    "# Download images\n",
    "for i, link in enumerate(image_links):\n",
    "    try:\n",
    "        response = requests.get(link)\n",
    "        with open(os.path.join(keyword, f\"image_{i}.jpg\"), \"wb\") as f:\n",
    "            f.write(response.content)\n",
    "        print(f\"Image {i} downloaded successfully\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error downloading image {i}: {e}\")\n",
    "\n",
    "# Close the browser\n",
    "driver.quit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "317a2020-30b9-4197-81ab-2769e4c10624",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6c9af729-8eba-4c89-8d0f-9e9744a04820",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
